### ISSUE TITLE
Data is coming back as HTML

### ISSUE THREAD

**Issue by naturalc** [robregonm/yii2-pdf#13]
I'm running a view and getting back HTML not PDF.  is there something else that needs to be done?

config

    'response' => [
            'formatters' => [
                'html' => [
                    'class' => 'yii\web\HtmlResponseFormatter',
                ],
                'pdf' => [
                    'class' => 'robregonm\pdf\PdfResponseFormatter',
                    'mode' => '',
                    'format' => 'A4',
                    'defaultFontSize' => 0,
                    'defaultFont' => '',
                    'marginLeft' => 15,
                    'marginRight' => 15,
                    'marginTop' => 16,
                    'marginBottom' => 16,
                    'marginHeader' => 9,
                    'marginFooter' => 9,
                ]
            ]
        ],

     $file = $this->getPdf(new Report($id));

    private function getPdf($report){
        Yii::$app->response->format = 'pdf';

        Yii::$container->set(Yii::$app->response->formatters['pdf']['class']);

        $this->layout = '//attachment';

        return $this->render('pdf/actionplan', ['model' => $report]);
    }

when I get the "pdf" I can't open it because its "corrupt" but the value in side is text and its the HTML from the view.  am I doing something wrong?  Should there be some headers or something?

**Comment by naturalc** [comment]
I've traced through step by step, robregonm\pdf\PdfResponseFormatter is never called....

**Comment by robregonm** [comment]
`getPdf` method should be an action.
Something like this should work:

```php
public function actiontPdf($id){
    $report = new Report($id)
    Yii::$app->response->format = 'pdf';
    Yii::$container->set(Yii::$app->response->formatters['pdf']['class']);

    $this->layout = '//attachment';

    return $this->render('pdf/actionplan', ['model' => $report]);
}
```

**Comment by naturalc** [comment]
I changed it to actionPdf but pdfresponseformatter.php is still not called and the render returns HTML

**Comment by naturalc** [comment]
go head and delete this conversation, I ended up going with a different extension that worked out of the box, however, thank you for providing this extension for use, it is much appreciated!
