### ISSUE TITLE
Got an Issue

### ISSUE THREAD

**Issue by aaesis** [robregonm/yii2-pdf#16]
Converted HTML to PDf

how will you implement this pdf functionality

http://mpdf1.com/manual/index.php?tid=152

it seems it has no documentation

**Comment by robregonm** [comment]
Two ways:
1. Using beforeRender() event (line 93 of PdfResponseFormatter class)
2. Using mpdf HTML tag for that purpose: http://mpdf1.com/manual/index.php?tid=176

Feel free to ask if you need more details or have more questions.

**Comment by aaesis** [comment]
thanks rob! I am satisfied of your answer. You can definitely close this question. Thanks again! great job!
