### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by blonder413** [robregonm/yii2-pdf#17]
I try with the example code and I have this problem:

`exception 'MpdfException' with message 'WriteHTML() requires $html be an integer, float, string, boolean or an object with the __toString() magic method.'`

**Comment by wokster** [comment]
This error is a consequence of another error when rendering
Try replare
`$this->layout = '//print';
        return $this->render('myview', []);`
to
`return $this->renderAjax('myview', []);`

**Comment by blonder413** [comment]
it's problem of my layout, it works with renderAjax, I have to do a new layout. Thank you.

**Comment by J-jack-K** [comment]
I have the same problem. In mpdf.php seems $html is an array and not a string.
I can't understand how to solve.
with return $this->renderAjax('myview', []); I can view the content correctly but not in PDF format

**Comment by J-jack-K** [comment]
Sorry solved. I'had an error writing folder mpdf/ttfontdata.
