### ISSUE TITLE
exception 'ReflectionException' with message 'Class robregonm\pdf\PdfResponseFormatter does not exist

### ISSUE THREAD

**Issue by hdushku** [robregonm/yii2-pdf#19]
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Class robregonm\pdf\PdfResponseFormatter does not exist' in /var/sentora/hostdata/zadmin/public_html/.../vendor/yiisoft/yii2/di/Container.php:422
Previous exception:
exception 'yii\base\ErrorException' with message 'file_put_contents(/var/sentora/hostdata/zadmin/public_html/.../vendor/mpdf/mpdf/ttfontdata/xbriyaz.GSUBGPOStables.dat): failed to open stream: Permission denied' in /var/sentora/hostdata/zadmin/public_html/.../vendor/mpdf/mpdf/classes/ttfontsuni.php:1264

**Comment by Sensetivity** [comment]
I have same error

**Comment by Sensetivity** [comment]
For my case error above took place when PHP process don't have enough memory.

**Comment by robregonm** [comment]
- Please check that you are using the lastest version of Yii 2.0 and this package (of course), so you should update composer too.
- Please, provide the line was running when this error appeared.

**Comment by robregonm** [comment]
This seems to be an error related to memory and/or wrong way to update composer packages. Closing.
