### ISSUE TITLE
mPDF version without upper bound in composer.json

### ISSUE THREAD

**Issue by finwe** [robregonm/yii2-pdf#20]
Hi,

I notice that your composer.json mpdf constraint is missing an upper bound. This will cause problems in following weeks when mPDF v 7.0 stable is out - it has a changed namespace, structure and constructor parameters.

This is a heads up, you might want to change your constraint or prepare your code for mPDF 7.0.

**Comment by robregonm** [comment]
Thanks for the heads up. I'll make the changes.
