### ISSUE TITLE
Error with upper mpdf in last commit

### ISSUE THREAD

**Issue by Anarchy-avk** [robregonm/yii2-pdf#21]
f9a8f33e608697599d44d3b9b0a93e7b9e34f0c3  
in this commit uppered php version but not mpdf version,
there for after update load last version of mpdf, that not compatible this your project.

**Comment by robregonm** [comment]
Your right, in fact, checking carefully, the version constraint should be for `mpdf`, not php. My bad. I'll fix it soon. Or if you can send a pull-request, it would be nice.

**Comment by robregonm** [comment]
Please, update to the latest version.
