### ISSUE TITLE
为什么在页面上面写有php代时会出错<?php echo $username;?>

### ISSUE THREAD

**Issue by huaiguoguo** [robregonm/yii2-pdf#25]
为什么在页面上面写有php代时会出错<?php echo $username;?>

页面会一直在加载当中，如果去掉 页面上的php代码的话，成功了，但是也很慢

![image](https://user-images.githubusercontent.com/1888094/38086476-11d87a42-3387-11e8-9636-49efd1f705ce.png)

![image](https://user-images.githubusercontent.com/1888094/38086492-24b82cca-3387-11e8-83a0-b3bccb643077.png)

![image](https://user-images.githubusercontent.com/1888094/38086504-312054ba-3387-11e8-8ae9-5bdc48532488.png)

![image](https://user-images.githubusercontent.com/1888094/38086532-4aa5102e-3387-11e8-8b66-43c4279f1938.png)

**Comment by robregonm** [comment]
Please, only in english.
